alunos = [
    "MARIA ROSÁRIO DE FÁTIMA DUARTE FERREIRA",
    "GABRIEL CARNEIRO BARROS",
    "LUIZ AUGUSTO XAVIER DE OLIVEIRA",
    "SEVERINO ITAMAR DA SILVA",
    "AMANDA CARDOSO RIBEIRO",
    "GABRIEL ALVES SABIA",
    "JULIANA BARBOSA FERREIRA",
    "ALEXANDRO HEITOR DOS SANTOS FERREIRA",
    "PEDRO CALDAS DE FARIAS",
    "GABRIELLA CUNHA MACIEL",
    "JULIO CESAR SOUZA RODRIGUES DOS SANTOS",
    "MIGUEL GUILHERME ALVES RODRIGUES",
    "LARA LORRANY GUEDES DIAS",
    "ALONSO DOS SANTOS SILVA",
    "PAULO VICTOR HAHN SIQUEIRA",
    "JESSICA CRISTINA GOMES PIMENTA DE OLIVEIRA",
    "DANIELLE MONTEIRO BRITO",
    "CARLOS HENRIQUE FELIX DA SILVA",
    "GABRIEL ANDRÉ DA SILVEIRA SILVA",
    "MIGUEL VÍTOR MENDES DA SILVA",
    "GUILHERME FEITOSA RODRIGUES DA SILVA",
    "MARIA LUIZA OLIVEIRA DE SÁ",
    "FRANCIELE MARIA FERREIRA",
    "ÁLEF CALEB AZEVEDO BRITO",
    "JOÃO FELLYPE ROCHA SANTANA",
    "PEDRO HENRIQUE ALVES BARBOSA RIBEIRO LEANDRO",
    "GILVANIR DOS SANTOS E SOUSA",
    "GABRIEL EVANGELISTA SILVA"
]

alunos = [a.title() for a in alunos]
alunos = sorted(alunos)

print("Total de alunos:", len(alunos))
for a in alunos:
    print(a)
